language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.3.7
  - DJANGO=1.4.13
  - DJANGO=1.5.8
  - DJANGO=1.6.5

matrix:
    exclude:
        - python: "3.2"
          env: DJANGO=1.3.7
        - python: "3.2"
          env: DJANGO=1.4.13

        - python: "3.3"
          env: DJANGO=1.3.7
        - python: "3.3"
          env: DJANGO=1.4.13

        - python: "3.4"
          env: DJANGO=1.3.7
        - python: "3.4"
          env: DJANGO=1.4.13



install:
  - pip install django==$DJANGO
  - python setup.py install

script: python run_tests.py
